version: "3.8"

services:
  redis:
    image: redis:5.0.14-bullseye
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "changepassword"
    networks:
      - ops_network

volumes:
  redis_data:
    name: redis_data
    driver: local
    driver_opts:
      type: none
      device: /data/redis
      o: bind

networks:
  ops_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br_ops_network
